require("local.core.options")
require("local.core.keymaps")
require("local.core.colorscheme")
require("local.packer")
require("local.plugin.lualine")
require("local.plugin.colorutils")
require("local.plugin.colorizer")
require("local.plugin.treesitter")
require("local.plugin.nvim-tree")

